# Generated by Django 5.1.5 on 2025-02-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='id',
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='cId',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
