# Generated by Django 5.1.5 on 2025-02-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='id',
        ),
        migrations.AddField(
            model_name='craftsman',
            name='cId',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
